# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "bb-shop-portal"
primary_region = "atl"

[build]

[env]
  PORT = "3000"
  SHOPIFY_APP_URL = "https://bb-shop-portal.fly.dev/"
  SCOPES = "write_products"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
