# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c9299f11648727ec0f0939900c319337"
application_url = "https://fairly-oak-stewart-comedy.trycloudflare.com"
embedded = true
name = "bb-shop-portal"
handle = "bb-shop-portal"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://fairly-oak-stewart-comedy.trycloudflare.com/auth/callback",
  "https://fairly-oak-stewart-comedy.trycloudflare.com/auth/shopify/callback",
  "https://fairly-oak-stewart-comedy.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
