# Learn more about configuring your Customer account UI extension:
# https://shopify.dev/api/customer-account-ui-extensions/unstable/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-01"

[[extensions]]
name = "Banner Card"
handle = "customer-account-ui"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/BannerCard.tsx"
target = "customer-account.order-index.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#network-access
# network_access = true

[extensions.settings]
  [[extensions.settings.fields]]
  key = "title"
  type = "single_line_text_field"
  name = "Title"
  [[extensions.settings.fields]]
  key = "description"
  type = "single_line_text_field"
  name = "Description"
  [[extensions.settings.fields]]
  key = "button_label"
  type = "single_line_text_field"
  name = "Button label"
  [[extensions.settings.fields]]
  key = "button_url"
  type = "single_line_text_field"
  name = "Button URL"
  description = "Enter a valid URL"
    [[extensions.settings.fields.validations]]
    name = "regex"
    value = "^https?://(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{2,256}\\.[a-z]{2,4}\\b([-a-zA-Z0-9@:%_\\+.~#?&//=]*)$"
